# global_costmap:
#   update_frequency: 2.5
#   publish_frequency: 2.5
#   transform_tolerance: 0.5
#   static_map: true
#   rolling_window: true
#   width: 15
#   height: 15
#   origin_x: -7.5
#   origin_y: -7.5
#   resolution: 0.1
#   inflation_radius: 0


# global_costmap:
#   update_frequency: 2.5
#   publish_frequency: 2.5
#   transform_tolerance: 0.5
#   static_map: true
#   rolling_window: true
#   width: 15
#   height: 15
#   origin_x: -7.5
#   origin_y: -7.5
#   resolution: 0.1
#   inflation_radius: 0


global_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.5

  static_map: true
 
